// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedstringtoguidonscheduleid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedstringtoguidonscheduleid));
        
        string IMigrationMetadata.Id
        {
            get { return "201705311949133_changed string to guid on schedule id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
